/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "/home/kali/Desktop/VLSI-Design/projects/HW_Trojans/NonHWT/source/non_hwt.v:6" *)
module non_active_hwt(A, B, C, D, Y);
  (* src = "/home/kali/Desktop/VLSI-Design/projects/HW_Trojans/NonHWT/source/non_hwt.v:14" *)
  input A;
  (* src = "/home/kali/Desktop/VLSI-Design/projects/HW_Trojans/NonHWT/source/non_hwt.v:15" *)
  input B;
  (* src = "/home/kali/Desktop/VLSI-Design/projects/HW_Trojans/NonHWT/source/non_hwt.v:16" *)
  input C;
  (* src = "/home/kali/Desktop/VLSI-Design/projects/HW_Trojans/NonHWT/source/non_hwt.v:17" *)
  input D;
  (* src = "/home/kali/Desktop/VLSI-Design/projects/HW_Trojans/NonHWT/source/non_hwt.v:18" *)
  output Y;
  wire _0_;
  wire _1_;
  wire _2_;
  wire _3_;
  INVX1 _4_ (
    .A(D),
    .Y(_0_)
  );
  INVX1 _5_ (
    .A(C),
    .Y(_1_)
  );
  NAND2X1 _6_ (
    .A(B),
    .B(A),
    .Y(_2_)
  );
  AOI21X1 _7_ (
    .A(_2_),
    .B(_1_),
    .C(_0_),
    .Y(_3_)
  );
  (* keep = 32'd1 *)
  BUFX2 _8_ (
    .A(_3_),
    .Y(Y)
  );
endmodule
